-- TowerAttributesModule
local TowerAttributes = {
	["Mahuna"] = {
		AttackSize = 2,
		AttackSpeed = 5,
		AttackType = "Line",
		CritDamage = 1.5,
		CritRate = 0.25,
		Damage = 5,
		DotDamage = 0,
		DotDuration = 0,
		Element = "Hydro",
		HybridAttack = false,
		Range = 15,
		SlowDuration = 0,
		SlowPercentage = 0,
		Type = "Ground",
		CCType="None",
		Rarity = "Mythic",
		Cost = 200,
		Level = 1,
		PlacementCap = 4,
		Idle = "ChosoIdle",
		Attack = "ChosoBloodBeam"
	},
	["Dedid"] = {
		AttackSize = 4,
		AttackSpeed = 3,
		AttackType = "Circle",
		CritDamage = 1.5,
		CritRate = 0.25,
		Damage = 8,
		DotDamage = 0,
		DotDuration = 0,
		Element = "Infernal",
		HybridAttack = true,
		Range = 20,
		SlowDuration = 0,
		SlowPercentage = 0,
		Type = "Hill",
		CCType="None",
		Rarity = "Epic",
		Cost = 300,
		Level = 1,
		PlacementCap = 3,
		Idle = "BaseIdle",
		Attack = "ChosoBloodBomb"
	},
	["Chozzi"] = {
		AttackSize = 4,
		AttackSpeed = 4,
		AttackType = "Circle",
		CritDamage = 1.5,
		CritRate = 0.25,
		Damage = 10,
		DotDamage = 0,
		DotDuration = 0,
		Element = "Physical",
		HybridAttack = true,
		Range = 20,
		SlowDuration = 0,
		SlowPercentage = 0,
		Type = "Ground",
		CCType="None",
		Rarity = "Legendary",
		Cost = 450,
		Level = 1,
		PlacementCap = 2,
		Idle = "ChosoIdle",
		Attack = "ChosoBloodBomb"
	}
	-- Add more towers as needed
}

return TowerAttributes
